- Engine/Modules/AdminBackend/Services/SidebarNavigationService.php
> some refactorings

- Engine/Modules/Core/Models/DiscriminatorEntry.php
- Engine/Modules/Core/Models/DiscriminatorEntryListener.php
- Engine/Modules/Core/Models/ForgeDataBase.php
- Engine/Modules/Cronjob/.phpstorm/.ide-toolbox.metadata.json
- Engine/Modules/Cronjob/.phpstorm/.phpstorm.meta.php
- Engine/Modules/Cronjob/Abstracts/AbstractCronjobHandler.php
- Engine/Modules/Cronjob/Bootstrap.php
- Engine/Modules/Cronjob/CronjobStatics.php
- Engine/Modules/Cronjob/Cronjobs/LogCleanupCronjob.php
- Engine/Modules/Cronjob/Models/AbstractCronjob.php
- Engine/Modules/Cronjob/Models/CommandCronjob.php
- Engine/Modules/Cronjob/Models/CustomCronjob.php
- Engine/Modules/Cronjob/Services/CronjobService.php
Pull request after console module pull request
> Cronjob module

- Engine/Modules/TemplateEngine/Models/ScssVariable.php
- Engine/Modules/TemplateEngine/Services/CssAssetService.php
- Engine/Modules/TemplateEngine/Services/ScssVariableService.php
Added ScssVariable functionality
> Added ScssVariable functionality

- Engine/Modules/Core/Abstracts/AbstractViewManager.php
- Engine/Modules/SystemSettings/Bootstrap.php
- Engine/Modules/SystemSettings/Controller/Backend/SystemSettingsController.php
- Engine/Modules/SystemSettings/Controller/Backend/SystemSettingsGroupController.php
- Engine/Modules/TemplateEngine/Bootstrap.php
- Engine/Modules/TemplateEngine/Exceptions/InvalidScssVariableException.php
- Engine/Modules/TemplateEngine/Manager/TemplateManager.php
- Engine/Modules/TemplateEngine/Manager/ViewManager.php
- Engine/Modules/TemplateEngine/Middleware/AssetsMiddleware.php
- Engine/Modules/TemplateEngine/Models/ScssVariable.php
- Engine/Modules/TemplateEngine/Models/Template/Template.php
- Engine/Modules/TemplateEngine/Services/BaseAssetService.php
- Engine/Modules/TemplateEngine/Services/CssAssetService.php
- Engine/Modules/TemplateEngine/Services/JsAssetService.php
- Engine/Modules/TemplateEngine/Services/ScssVariableService.php
- Engine/Modules/TemplateEngine/Services/StaticAssetService.php
- Engine/Modules/TemplateEngine/Services/TemplateAssetService.php
- Engine/Modules/TemplateEngine/Services/TemplateManagementService.php
- Engine/Modules/TemplateEngine/Services/TemplateRenderService.php
- Engine/Modules/TemplateEngine/Twig/CustomTwig.php
- Engine/Modules/TemplateEngine/Twig/TwigEnvironment.php
- Engine/Modules/TemplateEngine/Twig/TwigFileSystemLoader.php
- Engine/Modules/TemplateEngine/Twig/TwigOforgeDebugExtension.php
Reformatting and cleam up: TemplateEngine, SystemSettings
> Reformatting and cleam up: TemplateEngine, SystemSettings

- doc/conventions/code.md
- doc/conventions/index.md
- doc/conventions/phpdoc.md
- doc/development/console.md
- doc/development/cronjob.md
- doc/development/index.md
- doc/index.md
- doc/installation/environment.md
- doc/installation/index.md
- doc/installation/requirements.md
Contains:
- Guides for cronjob & console development
- Conventions for code and phpdoc
- Environment notes
- Requirements
> Initial documentation

- Engine/Modules/Core/Abstracts/AbstractModel.php
- Engine/Modules/Notifications/Abstracts/AbstractNotificationService.php
- Engine/Modules/Notifications/Bootstrap.php
- Engine/Modules/Notifications/Models/BackendNotification.php
- Engine/Modules/Notifications/Services/BackendNotificationService.php
- Engine/Modules/SystemSettings/Bootstrap.php
- Engine/Modules/TemplateSettings/Bootstrap.php
- Themes/Base/Backend/SystemSettings/Index.twig
> Added NotificationService

- Engine/Modules/AdminBackend/Services/BackendNavigationService.php
- Engine/Modules/Notifications/Bootstrap.php
- Engine/Modules/Notifications/Controller/BackendNotificationController.php
- Engine/Modules/Notifications/Services/BackendNotificationService.php
- Engine/Modules/TemplateExtensions/Twig/BackendExtension.php
- Themes/Base/Backend/Master/Components/PageHeader/Messages.twig
> Added NotificationController

- Engine/Modules/CMS/Controller/Backend/PagesController.php
- Themes/Base/Backend/Pages/ContentTypeList.twig
- Themes/Base/Backend/Pages/Index.twig
- Themes/Base/Backend/Pages/PageContent.twig
- Themes/Base/Backend/Pages/PageJsTree.twig
- Themes/Base/Backend/__assets/js/cms.page.controller.js
- Themes/Base/Backend/__assets/scss/all.scss
- Themes/Base/Backend/__assets/scss/cms/content-types.scss
- Themes/Base/Backend/__assets/scss/cms/dummy-content.scss
- Themes/Base/Backend/__assets/scss/cms/page-builder-content.scss
- Themes/Base/Backend/__assets/scss/cms/page-builder.scss
- Themes/Base/Backend/__assets/scss/cms/page-jstree.scss
- Themes/Base/ContentTypes/RichText/PageBuilder.twig
- Themes/Base/ContentTypes/Row/PageBuilder.twig
- docker/mysql/init/init.sql
- cleaned up cms twig files
- modified page builder design
> - added all cms dummy data to docker init sql file

- Engine/Modules/Core/Manager/Routes/RouteManager.php
- Engine/Modules/Core/Middleware/DebugModeMiddleware.php
- Engine/Modules/Session/Middleware/SessionMiddleware.php
- Plugins/Helpdesk/Views/Plugins/Helpdesk/Backend/BackendHelpdesk/Index.twig
- Themes/Base/Backend/CRUD/Index.twig
- Themes/Base/Backend/Dashboard/Help.twig
- Themes/Base/Backend/Dashboard/Index.twig
- Themes/Base/Backend/Dashboard/Tim.twig
- Themes/Base/Backend/DocumentationUI/Index.twig
- Themes/Base/Backend/Master/Index.twig
- Themes/Base/Backend/Pages/Index.twig
- Themes/Base/Frontend/Master.twig
Added system debug and removed all o_dump()'s from templates
> Added system debug and removed all o_dump()'s from templates

- Engine/Modules/Core/Abstracts/AbstractDatabaseAccess.php
- update phpdoc
- rename repository property to properties
- constructor models parameter: allow single string model class parameter
> Refactoring AbstractDatabaseAccess

- Engine/Modules/TemplateEngine/Core/Manager/ViewManager.php
Merging of lists of list
Example:
```
a = [
'entries' => [
[1]
]
]
a = [
'entries' => [
[2]
]
]
=
c = [
'entries' => [
[1],
[2],
]
]
```
> array_merge_recursive_ex: Merging of lists of list

- Engine/Modules/CRUD/Controller/Backend/BaseCrudController.php
- Themes/Base/Backend/CRUD/Components/Form.twig
- Themes/Base/Backend/CRUD/Components/Index/TableHeader.twig
- Themes/Base/Backend/CRUD/Components/ViewBase.twig
- Themes/Base/Backend/CRUD/Create.twig
- Themes/Base/Backend/CRUD/Delete.twig
- Themes/Base/Backend/CRUD/Update.twig
- Themes/Base/Backend/CRUD/View.twig
- Themes/Base/Backend/Master/Components/Content/BreadCrumbs.twig
- Themes/Base/Backend/Master/Components/Content/Header.twig
Backend page header & breadcrumb
- set for crud actions
- make favorite header button deactivatable
Minimal filter implementation & bugfix missing table column & form property labels
> CRUD Update

- Engine/Modules/CRUD/Controller/Backend/BaseCrudController.php
- Themes/Base/Backend/CRUD/Components/ViewBase.twig
- Themes/Base/Backend/Master/Components/Content/BreadCrumbs.twig
- Fix breadcrump url named parameters
- Fix merge on null in CRUD views
> CRUD breadcrump & merge on null in crud views

- Engine/Modules/Core/Manager/Services/ServiceManager.php
- Engine/Modules/Core/Services/PluginStateService.php
- Bugfix duplicate registering of services
- dependencies check in plugin install
> Duplicate Service-Registering-Bug & Install-Depency-Check

- Plugins/FrontendUserManagement/Controller/Frontend/LoginController.php
- Plugins/FrontendUserManagement/Controller/Frontend/RegistrationController.php
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Frontend/Components/Forms/LoginForm.twig
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Frontend/Components/Forms/RegistrationForm.twig
Installation of referrer in twig (meta.route.referrer) and redirect to referrer (if available) in controller
> LoginRegistration-Referrer

- Plugins/Helpdesk/Services/HelpdeskTicketService.php
- Plugins/Messenger/Bootstrap.php
> fixed support error

- Themes/Base/Frontend/__assets/js/commons.js
- Refactoring load more script
- extend Oforge.updateQueryString, add optional removeEmpty parameter
> Refactorings

- Engine/Modules/AdminBackend/Core/Bootstrap.php
- Engine/Modules/Core/Bootstrap.php
- Engine/Modules/Core/Services/ConfigService.php
- Engine/Modules/TemplateEngine/Core/Twig/TwigFlash.php
- Themes/Base/Backend/CRUD/Components/ViewBase.twig
- Themes/Base/Backend/Master/Components/Content/Header.twig
- Themes/Base/Backend/Master/Index.twig
- Themes/Base/Backend/Plugin/Components/FormKeepDataBase.twig
- Themes/Base/Backend/SystemSettings/GroupIndex.twig
- doc/index.md
- doc/twig/index.md
Core
- extend twig flash exception message with "Click for Details"-note
- move system settings in core bootstrap
- move twig data "meta.page.favoriteButton" to "meta.backend.favoriteButton"
- add config "backend_sidebar_collapsed_default"
& twig optional twig data "meta.backend.sidebar"
for toggling backend sidebar by config/twig data
Start documentation of twig data
AdminBackend-Settings: sort order of groups
> Different small refactorings

- Plugins/Insertion/Bootstrap.php
- Plugins/Insertion/Controller/Backend/BackendAttributeController.php
- Plugins/Insertion/Controller/Backend/BackendInsertionTypeController.php
- Plugins/Insertion/Services/AttributeService.php
- Plugins/Insertion/Services/InsertionTypeService.php
- Plugins/Insertion/Views/Plugins/Insertion/Backend/BackendInsertionType/Edit.twig
- Plugins/Insertion/Views/Plugins/Insertion/Backend/BackendInsertionType/Index.twig
- Themes/Base/Backend/__assets/js/editable-data-table.js
Added InsertionType to Backend and changes on Insertion Attributes
> Dev Added InsertionType to Backend and changes on Insertion Attributes

- Engine/Modules/Core/Models/Endpoint/Endpoint.php
- Engine/Modules/Core/Services/EndpointService.php
- Themes/Base/Backend/CRUD/Components/Form.twig
- Themes/Base/Backend/CRUD/Components/ViewBase.twig
- Themes/Base/Backend/Plugin/Components/FormKeepDataBase.twig
- add parentName
- add context (Module/Plugin name)
- update crud views
> Extending Endpoints

- Engine/Modules/Core/Bootstrap.php
- Engine/Modules/Core/Helper/DateTimeFormatter.php
- Engine/Modules/Core/Services/ConfigService.php
- Engine/Modules/TemplateEngine/Extensions/Twig/AccessExtension.php
- Plugins/Blog/Controller/Backend/PostController.php
- Plugins/Blog/Controller/Frontend/BlogController.php
- Plugins/Blog/Services/RatingService.php
- Plugins/Blog/Views/Plugins/Blog/Frontend/Category/PostEntry.twig
- Plugins/Blog/Views/Plugins/Blog/Frontend/Post/CommentEntry.twig
- Plugins/Blog/Views/Plugins/Blog/Frontend/Post/PostMeta.twig
Blog-RatingService: Include addition user isset check
Core:
- ConfigService: caching of requested config values, (cache-update on config update)
- add DateTimeFormatter
- add configs for DateTimeFormatter
TemplateEngine - AccessExtension:
- add filter formatDate, formatDatetime, formatTime (delegates to DateTimeFormatter)
Blog: move datetime formatting in twig
> Twig extension

- Themes/Base/Backend/Master/Components/PageHeader/Topbar/Notifications.twig
- Themes/Base/Backend/SystemSettings/GroupIndex.twig
- Themes/Base/Backend/SystemSettings/Index.twig
- Themes/Base/Frontend/Components/Header/Logo.twig
- Replace absolute uris with twig/slim url function
- Add TODO for missing frontend route in Logo
> Fix: Uris in Twig

- Plugins/Blog/Controller/Backend/CategoryController.php
- Plugins/Blog/Controller/Backend/PostController.php
- Plugins/Blog/Models/Category.php
- Plugins/Blog/Models/Post.php
- Plugins/Blog/Services/CategoryService.php
- Plugins/Blog/Services/PostService.php
- Themes/Base/Backend/CRUD/Components/Editor/Bool.twig
CRUD: fix switch checked default value
Plugin Blog:
- add active property to category & post
- Frontend: only active categories & posts (of category) list
> Plugin blog

- Engine/Modules/CRUD/Controller/Backend/BaseCrudController.php
- Engine/Modules/CRUD/Services/GenericCrudService.php
- Plugins/FrontendUserManagement/Services/FrontendUserService.php
- Plugins/Helpdesk/Controller/Backend/BackendHelpdeskSettingsController.php
- Themes/Base/Backend/CRUD/Components/Index/FilterBar.twig
- Themes/Base/Backend/CRUD/Index.twig
- Themes/Base/Backend/__assets/js/imports.cfg
- Themes/Base/Backend/__assets/js/modules/crud/scripts.js
- Themes/Base/Backend/__assets/js/oforge-functions.js
FrontendUserService: fix index error/warning
CRUD:
- Prevent empty query filter keys
- bugfix: update(s) not flushed
- include query params in index form
- update flush: reverse optional flush (now true)
> FrontendUserService fix, CRUD query params, CRUD update flush bugfix

- Plugins/FrontendUserManagement/Bootstrap.php
- Plugins/FrontendUserManagement/Controller/Backend/BackendFrontendUserManagementController.php
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Backend/BackendFrontendUserManagement/CRUD/RenderContactEmail.twig
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Backend/BackendFrontendUserManagement/CRUD/RenderFirstName.twig
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Backend/BackendFrontendUserManagement/CRUD/RenderLastName.twig
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Backend/BackendFrontendUserManagement/CRUD/RenderNickName.twig
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Backend/BackendFrontendUserManagement/CRUD/RenderPhoneNumber.twig
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Backend/BackendFrontendUserManagement/Create.twig
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Backend/BackendFrontendUserManagement/Delete.twig
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Backend/BackendFrontendUserManagement/Index.twig
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Backend/BackendFrontendUserManagement/Update.twig
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Backend/BackendFrontendUserManagement/View.twig
Added Backend overview for FrontendUsers
> Added Backend overview for FrontendUsers

- Plugins/Faq/Views/Plugins/Faq/Frontend/FrontendFaq/Index.twig
- Plugins/Insertion/Views/Frontend/__assets/scss/all.scss
- Plugins/Insertion/Views/Frontend/__assets/scss/header/_header.scss
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Header/Header.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/Profile.twig
- Themes/Base/Frontend/__assets/js/collapse.js
- Themes/Base/Frontend/__assets/js/imports.cfg
- Themes/Base/Frontend/__assets/scss/components/_button.scss
- Themes/Base/Frontend/__assets/scss/components/_collapse.scss
- Themes/Base/Frontend/__assets/scss/components/_components.scss
- FAQ Frontend
- Insertion Header Image
> FAQ Frontend, Account Frontend

- Plugins/Insertion/Controller/Frontend/FrontendInsertionController.php
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/DetailSearch.twig
> Added DetailSearchPage

- Plugins/Insertion/Controller/Backend/BackendInsertionTypeController.php
- Plugins/Insertion/Models/InsertionType.php
- Plugins/Insertion/Models/InsertionTypeAttribute.php
- Plugins/Insertion/Services/InsertionTypeService.php
- Plugins/Insertion/Views/Plugins/Insertion/Backend/BackendInsertionType/Edit.twig
- Themes/Base/Backend/__assets/js/editable-data-table.js
>  Added QuickSearch

- Plugins/Messenger/Controller/Frontend/MessengerController.php
>  Fixed Messenger send mail bug

- Plugins/Messenger/Controller/Frontend/MessengerController.php
> Fixed Messenger send mail bug

- Plugins/Messenger/Controller/Frontend/MessengerController.php
>  Fixed Messenger send mail bug 

- Engine/Modules/CRUD/Controller/Backend/BaseCrudController.php
- Engine/Modules/I18n/Bootstrap.php
- Engine/Modules/I18n/Controller/Backend/I18n/LanguageController.php
- Engine/Modules/I18n/Controller/Backend/I18n/SnippetsController.php
- Engine/Modules/I18n/Helper/I18N.php
- Engine/Modules/I18n/Services/InternationalizationService.php
- Engine/Modules/TemplateEngine/Extensions/Twig/AccessExtension.php
- Themes/Base/Backend/CRUD/Components/Form.twig
- Themes/Base/Backend/CRUD/Components/Index/FilterBar.twig
- Themes/Base/Backend/CRUD/Components/Index/PaginationRow.twig
- Themes/Base/Backend/CRUD/Components/Index/RowAction/Delete.twig
- Themes/Base/Backend/CRUD/Components/Index/RowAction/Update.twig
- Themes/Base/Backend/CRUD/Components/Index/RowAction/View.twig
- Themes/Base/Backend/CRUD/Components/Index/Table.twig
- Themes/Base/Backend/CRUD/Components/Index/TableHeader.twig
- Themes/Base/Backend/CRUD/Components/Renderer/Image.twig
- Themes/Base/Backend/CRUD/Components/Renderer/Select.twig
- Themes/Base/Backend/CRUD/Index.twig
- extend translate function:
default value array with languageISO=>$languageDefault
- update i18n calls & controller i18n configs in I18N, CRUD
> I18n extend translate function for array default values

- Themes/Base/Backend/Components/Image.twig
- Themes/Base/Backend/Media/Index.twig
- Themes/Base/Backend/__assets/js/cms/content_type/gallery.js
- Themes/Base/Backend/__assets/js/media.js
- Themes/Base/ContentTypes/Gallery/PageBuilderForm.twig
- add config (clear, reset) for hiding buttons
- add reset button
> ImageField, reset, clear, bttons configurable

- Plugins/Helpdesk/Controller/Backend/BackendHelpdeskController.php
- Plugins/Helpdesk/Services/HelpdeskMessengerService.php
- Plugins/Messenger/Abstracts/AbstractMessengerService.php
- Plugins/Messenger/Controller/Frontend/MessengerController.php
- Plugins/Messenger/Models/Message.php
- Plugins/Messenger/Services/FrontendMessengerService.php
Messenger/Helpdesk Refactoring
> Messenger/Helpdesk Refactoring

- Plugins/Messenger/Controller/Frontend/MessengerController.php
- Plugins/Messenger/Models/Conversation.php
Added permission check for conversations
Added hashing for conversation id
> Messenger changes

- Engine/Modules/AdminBackend/KeyValueStore/Controller/Backend/KeyValueStoreController.php
- Themes/Base/Backend/Pages/PageBuilderContent.twig
- Themes/Base/Backend/__assets/scss/cms/page-builder.scss
- Themes/Base/ContentTypes/Gallery/PageBuilderForm.twig
- Themes/Base/ContentTypes/Image/PageBuilderForm.twig
- Themes/Base/ContentTypes/List/PageBuilder.twig
- Themes/Base/ContentTypes/Row/PageBuilder.twig
- enable KeyValueStoreController-delete
- add icon in sortable handler
> Small changes: KeyValueStoreController, CMS-Sortables

- Engine/Modules/Console/Commands/Service/ServiceRunCommand.php
- Engine/Modules/Core/Helper/CsvHelper.php
- Engine/Modules/I18n/Services/InternationalizationService.php
- Add CsvHelper class for csv writing & reading (by SplFileObject).
- Refactoring of InternationalizationService::insertFromCsv
- rename to importFromCsv
- using CsvHelper class for reading
- Change ServiceRunCommand output: if not scalar, use print_r to convert to string
> CsvHelper class, InternationalizationService::insertFromCsv, ServiceRunCommand output

- Engine/Modules/Core/Helper/CsvHelper.php
- Engine/Modules/I18n/Services/InternationalizationService.php
remove skipping of first row in import
> I18N::importFromCsv

- Engine/Modules/Core/Bootstrap.php
- Engine/Modules/TemplateEngine/Core/Services/CssAssetService.php
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Frontend/Components/Forms/RegistrationForm.twig
- Plugins/Helpdesk/Views/Frontend/__assets/scss/all.scss
- Plugins/Helpdesk/Views/Plugins/Helpdesk/Frontend/Components/Content/TicketList.twig
- Plugins/Insertion/Views/Frontend/__assets/scss/_panel.scss
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/Contact.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/Report.twig
added source maps (for frontend scope):
- new config key in backend (css_source_maps) -> set true for source mapping
(this will disable css - minification)
- adjusted css compilation process in order to make source mapping work with given library
> Source Maps, Frontend

- Plugins/Blog/Views/Plugins/Blog/Frontend/Post/CommentEntry.twig
- Plugins/FrontendUserManagement/Services/RegistrationService.php
missing details & address because not created on user registration
> Blog MS bug fix

- Engine/Modules/Core/Helper/RouteHelper.php
- Engine/Modules/Core/Manager/Slim/RouteMiddleware.php
- Engine/Modules/Media/Twig/MediaExtension.php
- Engine/Modules/TemplateEngine/Core/Services/CssAssetService.php
- Engine/Modules/TemplateEngine/Core/Services/JsAssetService.php
- Engine/Modules/TemplateEngine/Extensions/Services/UrlService.php
- Engine/Modules/TemplateEngine/Extensions/Twig/SlimExtension.php
- Plugins/FrontpageContentTypes/ContentTypes/Customers.php
- Plugins/FrontpageContentTypes/ContentTypes/IconTileBasic.php
- Plugins/FrontpageContentTypes/ContentTypes/IconTileText.php
- Plugins/FrontpageContentTypes/ContentTypes/ImageTileLarge.php
- Plugins/FrontpageContentTypes/ContentTypes/ImageTileMedium.php
- Plugins/FrontpageContentTypes/ContentTypes/ImageTileSmall.php
- Plugins/FrontpageContentTypes/ContentTypes/TextIconPrefix.php
- Plugins/Insertion/Services/InsertionUrlService.php
- Plugins/Seo/Services/SeoUrlService.php
- Themes/Base/Frontend/Components/Header/Logo.twig
- Themes/Base/Frontend/Components/Header/LogoClaim.twig
- Themes/Base/Frontend/Components/Scripts.twig
- Themes/Base/Frontend/Master.twig
- missing key handling in FrontendContentTypes
- urls with base path
> Urls with base path, missing key handling in FrontendContentTypes

- Plugins/FrontpageContentTypes/Views/ContentTypes/Components/ImageTileContent.twig
- Plugins/FrontpageContentTypes/Views/Frontend/__assets/scss/components/_image-tile.scss
- Plugins/Insertion/Views/Frontend/Components/Main/TopSlider.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Breadcrumb.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/Detail.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/DetailAttributes/Multi.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/DetailAttributes/Single.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/Profile.twig
Fixes for Detailpage and Frontpage.
> Fixes, Fixes and Fixes.

- Engine/Modules/AdminBackend/Core/Controller/Backend/IndexController.php
- Engine/Modules/AdminBackend/Core/Controller/Backend/LoginController.php
- Engine/Modules/Auth/Middleware/SecureMiddleware.php
- Plugins/FrontendUserManagement/Controller/Frontend/LoginController.php
- Plugins/FrontendUserManagement/Middleware/FrontendSecureMiddleware.php
- Themes/Base/Backend/Login/Index.twig
- include flash messages
- add Flash message if no email or password or invalid
- change SecureMiddlewares flash messages content
- i18n labels
> (Backend)Login FlashMessages

- Plugins/Insertion/Views/Plugins/Messenger/Frontend/Components/Content/Messenger.twig
- Plugins/Messenger/Services/FrontendMessengerService.php
- Plugins/Messenger/Views/Frontend/__assets/scss/all.scss
- Plugins/Messenger/Views/Plugins/Messenger/Frontend/Components/Content/Messenger.twig
- messenger: added counting limit of 10 messages
- messenger: documentation
- messenger: template adjustments
> Fixes, messenger

- Plugins/Helpdesk/Views/Frontend/__assets/js/chat.js
- Plugins/Messenger/Services/FrontendMessengerService.php
- Plugins/Messenger/Views/Frontend/__assets/scss/all.scss
- Plugins/Messenger/Views/Plugins/Messenger/Frontend/Components/Content/Messenger.twig
- chat will now focus on user's last seen message
> Frontend Messenger scrolling chat

- Engine/Modules/Mailer/Services/MailService.php
- Plugins/Helpdesk/Views/Plugins/Messenger/Frontend/Components/Content/Messenger.twig
- Plugins/Insertion/Controller/Backend/BackendInsertionController.php
- Plugins/Insertion/Views/Plugins/Insertion/Backend/BackendInsertion/CRUD/Form.twig
- Plugins/Messenger/Views/Frontend/__assets/scss/all.scss
- fixed messenger icons
- added mails for insertion approval
> Messenger, Backend Insertion Moderation

- Plugins/Helpdesk/Services/HelpdeskTicketService.php
- Plugins/Messenger/Controller/Frontend/MessengerController.php
- messenger no conversation bug fixed
- sorted helpdesk tickets by date
> Fixes / Adjustments

- Plugins/Helpdesk/Controller/Backend/BackendHelpdeskController.php
- Plugins/Helpdesk/Controller/Frontend/FrontendHelpdeskController.php
- Plugins/Helpdesk/Models/Ticket.php
- Plugins/Helpdesk/Services/HelpdeskMessengerService.php
- Plugins/Helpdesk/Services/HelpdeskTicketService.php
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendUsersInsertion/Index.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendUsersInsertion/Profile.twig
- Plugins/Messenger/Models/Conversation.php
- Plugins/Messenger/Services/FrontendMessengerService.php
Account:
- insertion listing: adjusted frontend
- insertion profile edit: localisation
Helpdesk Tickets:
- adjusted conversation model
- added service method to change conversationStatus
- backend / frontend ticket close now implies correctly conversation close
> Account, Helpdesk fixes

- Plugins/Messenger/Views/Frontend/__assets/scss/all.scss
- Themes/Base/Frontend/__assets/scss/components/_icons.scss
- messenger: removed horizontal scroll bar (chrome)
- icons: added heartbeat animation
> Messenger & Top-Nav adjustments

- Engine/Modules/Mailer/Services/MailService.php
- Plugins/Insertion/Commands/SearchBookmarkCommand.php
- Plugins/Insertion/Cronjobs/SearchBookmarkCronjob.php
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendUsersInsertion/Bookmarks.twig
- Plugins/Messenger/Views/Frontend/__assets/scss/all.scss
- search bookmark cronjob / mail
- adjusted messenger icon
> Icon / Cronjob adjustments

- Plugins/FrontendUserManagement/Controller/Frontend/ForgotPasswordController.php
- Plugins/FrontendUserManagement/Controller/Frontend/LoginController.php
- Plugins/FrontendUserManagement/Services/FrontendUserLoginService.php
- Plugins/Helpdesk/Views/Frontend/__assets/js/chat.js
- Plugins/Messenger/Views/Frontend/__assets/scss/all.scss
- Plugins/Messenger/Views/Plugins/Messenger/Frontend/Components/Forms/MessageForm.twig
- added localisations
- added more detailed output on login process-errors
- deactivated chat input if there is no active conversation
> Account Controller, Messenger

- Engine/Modules/AdminBackend/Core/Services/DashboardWidgetsService.php
- Engine/Modules/TemplateEngine/Extensions/Twig/BackendExtension.php
move userID in parameter list (caching optimization)
> Backend-DashboardWidgetsService::getUserWidgets

- Engine/Modules/CRUD/Services/GenericCrudService.php
- Engine/Modules/UserManagement/Controller/Backend/UserManagementController.php
(Preparation for EMV-Mandanten)
> CRUD action events, Extendable BackendUserRoles

- Plugins/Insertion/Services/InsertionProfileProgressService.php
- Plugins/Insertion/Views/Backend/__assets/scss/_insertion.scss
- Plugins/Insertion/Views/Frontend/Components/Insertions/UserBookmarks.twig
- Plugins/Insertion/Views/Frontend/__assets/js/floating-button.js
- Plugins/Insertion/Views/Frontend/__assets/scss/_insertion.scss
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/Pages/PageBase.twig
- Themes/Base/Backend/__assets/js/select.js
- Themes/Base/Frontend/__assets/js/select.js
- Themes/Base/Frontend/__assets/js/update-src.js
- if the insertion type doesn't require any information in step 2 of the creation process, the user will be directed to step 3
- synced frontend / backend _insertion.scss
- newSearchResults: generating Link to Results
> Insertion Creation, Insertion Bookmark, NewSearchResults

- Engine/Modules/Core/Bootstrap.php
- Plugins/CookieConsent/Views/Frontend/__assets/scss/all.scss
- Plugins/Insertion/Commands/SearchBookmarkCommand.php
- added padding to cookie consent button to avoid overlap with scroll-to-top button
- added new core system config element to save domain name
- added (commented) translations to system/debug configs
- generate link for new-search-results mail
> Small Frontend Fix for Cookie Consent / Added Link to Search Results to NewSearchResults Mail

- Plugins/Insertion/Services/InsertionListService.php
> fixed Insertion sort bug

- Plugins/Insertion/Controller/Backend/BackendInsertionController.php
- Plugins/Insertion/Controller/Frontend/FrontendInsertionController.php
- Plugins/Insertion/Models/Insertion.php
- Plugins/Insertion/Services/InsertionService.php
- Plugins/Insertion/Views/Backend/__assets/js/attribute-edit.js
- Plugins/Insertion/Views/Frontend/__assets/js/imports.cfg
- Plugins/Insertion/Views/Frontend/__assets/js/view-counter.js
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/Detail.twig
> added insertion view counter

- Plugins/Insertion/Controller/Frontend/FrontendInsertionController.php
- Plugins/Insertion/Services/InsertionService.php
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/PageContent/3.twig
added autofill for address in insertion creation
> 41 autofill address

- Plugins/Insertion/Controller/Frontend/FrontendInsertionController.php
Fixed a problem where an exception was thrown if a user doesn't have any insertions.
> Ticket 41 autofill address.

- Plugins/Analytics/Views/Frontend/Layout.twig
> 63-analytics-opt-in-tracking

- Plugins/Insertion/Views/Frontend/__assets/scss/_create.scss
> Ticket #80 - Make Create Types equal height.

- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/Attributes/Date.twig
- Themes/Base/Frontend/__assets/js/datepicker.js
- Themes/Base/Frontend/__assets/js/imports.cfg
- Themes/Base/Frontend/__assets/js/moment.js
- Themes/Base/Frontend/__assets/js/pickaday.js
- Themes/Base/Frontend/__assets/scss/components/_components.scss
- Themes/Base/Frontend/__assets/scss/components/_pickaday.scss
- included pickaday.js
- included moment.js for compatible formatting
- changed input type
- adjusted styling
> Barockpinto#57 Added datepicker library

- Plugins/Insertion/Middleware/InsertionProfileProgressMiddleware.php
- fixed error if user doesn't exist (which prevented redirect to login)
> Barockpinto#50

- Themes/Base/Frontend/__assets/js/datepicker.js
- check document language and if localisation exists in datepicker.js, it will overwrite default (english) localisation
> added german localisation to datepicker

- Plugins/Helpdesk/Controller/Frontend/FrontendHelpdeskController.php
- added missing endpoint action doc
- also added translations
> #120 (closing support tickets)

- Engine/Modules/Core/Forge/ForgeSlimApp.php
- config.sample.php
- server error reporting via mail (log files in attachments)
- theme specific redirecting on server error (in production mode) -> 500.html
> Report Mail on 500

- Engine/Modules/Core/Forge/ForgeSlimApp.php
- config.sample.php
- set config key to boolean
- use absolute path to 500.html
> error mail adjustment

- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/PageContent/1.twig
- added modal view frontend code
- conditional load of module if content is available
> hotfix modal view on insertion creation

- Plugins/ImageUpload/Views/Frontend/Components/UppyLoad.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/PageContent/1.twig
> hotfix modal view

- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Sort.twig
- Themes/Base/Frontend/__assets/scss/base/_default.scss
- disable submit button and show tooltip
> disable toggleSearchBookmark if user is not logged in

- Plugins/Insertion/Views/Frontend/Components/Insertions/UserInsertion.twig
- Plugins/Insertion/Views/Frontend/__assets/scss/_product-list.scss
> insertion view counter in user insertions

- Plugins/Insertion/Views/Backend/__assets/scss/_product-list.scss
- $background is not defined for this context
> hotfix: replace variable in backend context

- Plugins/ImageUpload/Views/Frontend/Components/UppyLoad.twig
- Plugins/ImageUpload/Views/Frontend/__assets/js/uppy-loader.js
- Plugins/Insertion/Controller/Backend/BackendInsertionTypeController.php
- Plugins/Insertion/Models/InsertionType.php
- Plugins/Insertion/Views/Plugins/Insertion/Backend/BackendInsertionType/Edit.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/PageContent/1.twig
> InsertionType image required

- Engine/Modules/CRUD/Bootstrap.php
- Engine/Modules/CRUD/Controller/Backend/BaseCrudController.php
- Engine/Modules/CRUD/Enum/CrudFilterComparator.php
- Engine/Modules/CRUD/Services/GenericCrudService.php
- Engine/Modules/CRUD/Twig/CrudExtension.php
- Engine/Modules/TemplateEngine/Core/Services/TemplateRenderService.php
- Themes/Base/Backend/CRUD/Components/Editor.twig
- Themes/Base/Backend/CRUD/Components/Form.twig
- Themes/Base/Backend/CRUD/Components/Index/FilterBar.twig
- Themes/Base/Backend/CRUD/Components/Index/Table.twig
- Themes/Base/Backend/CRUD/Components/Index/TableCell.twig
- Themes/Base/Backend/CRUD/Components/Index/TableRowActions.twig
- Themes/Base/Backend/CRUD/Components/Renderer.twig
- Themes/Base/Backend/CRUD/Components/ViewBase.twig
- Themes/Base/Backend/CRUD/Index.twig
- Component magic loading (Enables overriding of individual components)
- include FilterComparator in & notIn
> CRUD updates

- Engine/Modules/AdminBackend/Core/Controller/Backend/DashboardController.php
- Engine/Modules/AdminBackend/Core/Controller/Backend/FavoritesController.php
- Engine/Modules/AdminBackend/Core/Controller/Backend/LogoutController.php
- Engine/Modules/AdminBackend/Core/Middleware/BackendSecureMiddleware.php
- Engine/Modules/Auth/Models/User/BackendUser.php
- Engine/Modules/CMS/Controller/Backend/AjaxController.php
- Engine/Modules/CMS/Controller/Backend/ElementsController.php
- Engine/Modules/CMS/Controller/Backend/PagesController.php
- Engine/Modules/Media/Controller/Backend/Media/AjaxController.php
- Engine/Modules/Notifications/Controller/BackendNotificationController.php
- Engine/Modules/UserManagement/Controller/Backend/ProfileController.php
- Engine/Modules/UserManagement/Controller/Backend/UserManagementController.php
- Add Permission level logged_in
- change level to logged_in of: Dasboard, Favorites, Logout, CMS, Profile
> Auth permission level quickfix

- Themes/Base/Frontend/__assets/scss/components/_image-upload.scss
> Image upload fix

- Plugins/Insertion/Controller/Backend/BackendInsertionTypeController.php
- Plugins/Insertion/Models/InsertionType.php
- Plugins/Insertion/Views/Frontend/Components/Insertions/Hint.twig
- Plugins/Insertion/Views/Plugins/Insertion/Backend/BackendAttribute/Edit.twig
- Plugins/Insertion/Views/Plugins/Insertion/Backend/BackendInsertionType/Edit.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/ProductPanel.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/Attributes/Boolean.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/Attributes/Text.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/PageContent/3.twig
Min and Max Values for Prices can now be defined in the Backend.
> #162 variable price ranges

- Plugins/Insertion/Views/Frontend/Components/Insertions/Hint.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/ProductPanel.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/Attributes/Boolean.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/Attributes/Text.twig
Show a typified Label for prices in listing.
> #179 price stud fee

- Plugins/Analytics/Views/Frontend/Layout.twig
- Plugins/CookieConsent/Views/Frontend/__assets/js/cookie-consent.js
- Added Google Tag Manager
- Added custom JavaScript event for cookie activation
> 178 google tag manager

- Themes/Base/Frontend/Master.twig
> Added script block in header

- Plugins/FrontendUserManagement/Controller/Frontend/RegistrationController.php
Added css class for registration success
>  Added css class for registration success

- Plugins/FrontendUserManagement/Controller/Frontend/RegistrationController.php
> fixed typo ... again

- Plugins/Messenger/Controller/Frontend/MessengerController.php
- Plugins/Messenger/Views/Plugins/Messenger/Frontend/Components/Forms/MessageForm.twig
Save message if session is expired
> Save message if session is expired

- Engine/Modules/Core/Abstracts/AbstractClassPropertyAccess.php
- Engine/Modules/Core/Abstracts/AbstractModel.php
Extract AbstractModel::fromArray|toArray in Subclass for Embedded (custom) objects in Doctrine (eg Embeddables).
> Extract AbstractModel::fromArray|toArray in Subclass

- Engine/Modules/I18n/Models/Snippet.php
ALTER TABLE `oforge_i18n_snippet` CHANGE `value` `value` LONGTEXT NOT NULL;
> I18n Snippet value type change to text (longtext instead of varchar 255)

- Engine/Modules/Mailer/Services/MailService.php
- Plugins/Insertion/Bootstrap.php
- Plugins/Insertion/Controller/Frontend/FrontendInsertionController.php
- redirect to login before user can type and submit a message
> User messages

- Engine/Modules/Mailer/Bootstrap.php
- Engine/Modules/Mailer/Services/MailService.php
- in order for this change to apply, delete modules table
- configuration: backend/settings/mailer -> toggle redirect "on", specify redirect recipient
> add toggle to redirect all outgoing mail to specified recipient

- Plugins/FrontendUserManagement/Services/RegistrationService.php
- Plugins/Insertion/Services/InsertionFeedbackService.php
- (feedback) if a user doesn't select a rating, set rating to value=-1
- (activate) catch error on non-existing guid
> Hotfix insertion feedback / Hotfix activate User Profile

- Engine/Modules/Core/Abstracts/AbstractController.php
Added missing abstract keyword to AbstractController
> Added missing abstract keyword to AbstractController

- Engine/Modules/AdminBackend/Cronjob/Controller/Backend/CronjobController.php
- Engine/Modules/Console/Services/ConsoleService.php
- Engine/Modules/Cronjob/Services/CronjobService.php
- Themes/Base/Backend/CRUD/Components/Editor/DateTime.twig
- Themes/Base/Backend/CRUD/Components/Index/Table.twig
- make cronjob next execution editable
- fix consoleService lifecycle
- add toggle active/inactive for cronjobs
> Cronjob Adjustments

- Engine/Modules/I18n/Helper/I18N.php
- Engine/Modules/I18n/Services/InternationalizationService.php
> Fix Language snippet creation

- Plugins/Insertion/Controller/Backend/BackendInsertionController.php
- add columns createdAt & updatedAt
- replace $_POST with $request->getParsedBodyParam
- cleanup
> 248 - backend insertions crud index change

- Engine/Modules/Auth/Services/AuthService.php
- Engine/Modules/Auth/Services/PasswordService.php
- Engine/Modules/UserManagement/.meta/.phpstorm.meta.php
- Engine/Modules/UserManagement/Bootstrap.php
- Engine/Modules/UserManagement/Services/BackendUserService.php
Refactoring of createAdmin service function
- move to UserManagement module
- simplify exist search
- extend to create every type of backend user (optional passing of password & role otherwise generate/default value)
PasswordService::generatePassword: removesame looking characters eg I1l
> Refactoring of createAdmin service function

- Plugins/FrontpageContentTypes/Views/Frontend/__assets/scss/components/_row.scss
-add generic class to center cms content at 50% width
> Add css class

- Engine/Modules/Media/Services/ImageCompressService.php
- Engine/Modules/Media/Twig/MediaExtension.php
- add blurred background images
> Top Insertion Slider

- Engine/Modules/Media/Services/ImageCompressService.php
- adjust file name when blurred
- add opacity filter
> Top Slider Background

- Engine/Modules/Console/Services/ConsoleService.php
- Engine/Modules/Core/Helper/BitmaskHelper.php
> Rename BinaryHelper to BitmaskHelper

- Plugins/Insertion/Controller/Backend/BackendInsertionController.php
- Plugins/Insertion/Models/Insertion.php
- Plugins/Insertion/Services/InsertionCreatorService.php
- Plugins/Insertion/Services/InsertionFormsService.php
- Plugins/Insertion/Services/InsertionUpdaterService.php
- Plugins/Insertion/Views/Backend/__assets/js/price-type-switch.js
- Plugins/Insertion/Views/Frontend/__assets/js/price-type-switch.js
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/ProductList.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/ProductPanel.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Search/Distance.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/Detail.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/DetailSidebar.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/PageContent/3.twig
- Plugins/Translation/Views/Plugins/Insertion/Frontend/FrontendInsertion/Detail.twig
- composer.json
New PriceType for Auction advertisement
some small fixes
> New PriceType for Auction advertisement

- Engine/Modules/AdminBackend/Core/Models/BackendNavigation.php
- Engine/Modules/AdminBackend/Core/Services/BackendNavigationService.php
- Themes/Base/Backend/Master/Components/Sidebar/Item.twig
Cherry pick of cms branch
- BackendNavigation: Extension by named params and query params
- Backend sidebar: Removing of empty sidebar blocks (0 level blocks)
> BackendNavigation: Extension by named params and query params

- Engine/Modules/CRUD/Controller/Backend/BaseCrudController.php
- Themes/Base/Backend/CRUD/Components/Editor/Input.twig
- Themes/Base/Backend/CRUD/Components/Editor/String.twig
- Themes/Base/Backend/CRUD/Components/Index/FilterType/Text.twig
> CRUD: Use list values as datalist in inputs

- Engine/Modules/Core/Helper/ArrayPhpFileStorage.php
> ArrayPhpFileStorage: extend file check with readable-check

- Engine/Modules/Auth/.meta/.phpstorm.meta.php
- Engine/Modules/Auth/Bootstrap.php
- Engine/Modules/Auth/Enums/InvalidPasswordFormatException.php
- Engine/Modules/Auth/Services/PasswordService.php
- Engine/Modules/CRUD/Controller/Backend/BaseCrudController.php
- Engine/Modules/CRUD/Services/GenericCrudService.php
- Engine/Modules/UserManagement/Controller/Backend/ProfileController.php
- Engine/Modules/UserManagement/Controller/Backend/UserManagementController.php
- Engine/Modules/UserManagement/Services/BackendUserService.php
- Engine/Modules/UserManagement/Services/BaseUsersCrudService.php
- Plugins/FrontendUserManagement/Controller/Frontend/AccountController.php
- Plugins/FrontendUserManagement/Controller/Frontend/ForgotPasswordController.php
- Plugins/FrontendUserManagement/Controller/Frontend/RegistrationController.php
- Plugins/SocialLogin/.meta/.phpstorm.meta.php
- Plugins/SocialLogin/Bootstrap.php
- Plugins/SocialLogin/Controller/Frontend/SocialLoginController.php
- Plugins/SocialLogin/Services/LoginConnectService.php
- Plugins/SocialLogin/Services/LoginProviderService.php
- Plugins/SocialLogin/Services/UserLoginService.php
- extract password format check in own function.
- password length is configurable now
- invalid password format messages (by exceptions)
- cleanup at usage positions
> #385 - Refactoring of password format check

- Engine/Modules/Core/Abstracts/AbstractBootstrap.php
- Engine/Modules/Core/Services/PluginStateService.php
- Plugins/Analytics/Bootstrap.php
- Plugins/Blog/Bootstrap.php
- Plugins/FrontendUserManagement/Bootstrap.php
- Plugins/Helpdesk/Bootstrap.php
- Plugins/Insertion/Bootstrap.php
> Handover keepData value to Bootstrap::uninstall

- Plugins/Insertion/Controller/Backend/BackendAttributeController.php
- Plugins/Insertion/Controller/Frontend/FrontendInsertionController.php
- Plugins/Insertion/Models/Insertion.php
- Plugins/Insertion/Services/InsertionListService.php
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Filter/Pedigree.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/ProductPanel.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/DetailSearch.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/PageContent/3.twig
- Plugins/Messenger/Controller/Frontend/MessengerController.php
- Plugins/Pedigree/Services/PedigreeService.php
Fixed missing email for message
> Fixed missing email for message

- Plugins/Messenger/Views/Frontend/__assets/scss/all.scss
- Plugins/Messenger/Views/Plugins/Messenger/Frontend/Components/Content/Messenger.twig
- Themes/Base/Frontend/__assets/js/imports.cfg
- Themes/Base/Frontend/__assets/js/make_urls_clickable.js
- Messeger chat message links css
- add Oforge.makeUrlsClickable function
- autorun on elements with class 'make_urls_clickable' & remove this class
> #431 Make links in Chat messages clickable

- Plugins/Insertion/Views/Frontend/Components/Insertions/UserBookmarks.twig
- Plugins/Insertion/Views/Frontend/Components/Insertions/UserInsertion.twig
- Plugins/Insertion/Views/Frontend/__assets/scss/_insertion.scss
- Plugins/Insertion/Views/Frontend/__assets/scss/_product-list.scss
- replace hard coded strings with i18n snippets
- correction of button title
- remove double a end tag
- style of overlay
> #330 Bookmark image overlay for deleted or deactivated insertions

- Plugins/FrontendUserManagement/Controller/Frontend/ForgotPasswordController.php
- Plugins/FrontendUserManagement/Controller/Frontend/RegistrationController.php
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Frontend/Components/Forms/LoginForm.twig
- Plugins/FrontendUserManagement/Views/Plugins/FrontendUserManagement/Frontend/Registration/ResendActivationLink.twig
- include link below login form
- mail insert page
- controller action for resending
- include link in RegisterConfirm mail template
> #247 Resending of registration activation link

- Plugins/Helpdesk/Views/Plugins/Helpdesk/Backend/BackendHelpdesk/Messenger.twig
- Plugins/Messenger/Views/Frontend/__assets/scss/all.scss
- Plugins/Messenger/Views/Plugins/Messenger/Frontend/Components/Forms/MessageForm.twig
- Themes/Base/Backend/__assets/js/imports.cfg
- Themes/Base/Backend/__assets/js/modules/textarea_autoresize.js
- Themes/Base/Frontend/__assets/js/imports.cfg
- Themes/Base/Frontend/__assets/js/textarea_autoresize.js
- add textarea autoresize function in oforge (initTextareaAutoresize)
- auto-autoresize textareas with 'data-autoresize' attribute
- include in Frontend-Messenger
- include in Backend-Helpdesk
> #000 textarea autoresize (height)

- Plugins/Insertion/Bootstrap.php
- Plugins/Insertion/Controller/Frontend/InsertionProvidersController.php
- Plugins/Insertion/Services/InsertionListService.php
- Plugins/Insertion/Services/InsertionProfileService.php
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/InsertionProviders/Index.twig
Additional changes in repos Premium, FrontendUserPageBuilder, AYH-Theme
> #288 InsertionProvidersOverview

- Engine/Modules/Core/Services/PluginStateService.php
Add callPluginBootstrapMethod method in PluginStateService to call install/activate method in Plugin Bootstrap class.
> Add callPluginBootstrapMethod method in PluginStateService

- .gitignore
- Plugins/GoogleAnalytics/Bootstrap.php
- Plugins/GoogleAnalytics/Views/Frontend/Layout.twig
Only gtag twig snippet & with settings
> Restoration of google analytics plugin (with gtag)

- .gitignore
- Engine/Modules/TemplateEngine/Core/Services/CssAssetService.php
- Themes/Base/Frontend/__assets/scss/components/header/_main-nav.scss
- composer.json
- Replace deprecated leafo/scssphp composer package with scssphp/scssphp
- gitignore theme configuration
Additional changes in Git Branches:
- AYH Theme
- CMS Plugin
- FrontendUserPageBuilder Plugin
> #363 nested menus

- Engine/Modules/Core/Forge/ForgeSettings.php
- Plugins/ReportErrorForm/Controller/FormController.php
- config.sample.php
- receiver configuration in config.php
- set opener to userID if logged
- replace access in ForgeSettings::get to ArrayHelper::dotGet
> Report error form changes

- Plugins/VideoUpload/Views/Frontend/__assets/js/video-upload.js
- Plugins/VideoUpload/Views/Frontend/__assets/scss/_video-upload.scss
- Plugins/VideoUpload/Views/Frontend/__assets/scss/all.scss
- Plugins/VideoUpload/Views/Plugins/VideoUpload/Frontend/Components/Content/VideoUpload.twig
- Themes/Base/Frontend/__assets/scss/components/_upload.scss
Refactored and extended version Nestors code, thumbnail replacing is now optional
> #241 video upload image

- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendInsertion/DetailSidebar.twig
Removed visible contact on Insertion DetailSidebar.twig
> Removed visible contact on Insertion DetailSidebar.twig

- Plugins/Insertion/.meta/.phpstorm.meta.php
- Plugins/Insertion/Middleware/InsertionProfileProgressMiddleware.php
\+ branch in ayh-frontenduser-profile-cms repo
> #446-profile-progress-cms-adjustments

- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Search/Price.twig
twig parent passes insertionType, depending on the insertion type, we adjust the step size in the input field for price.
> include variable stepSizes for price input

- Plugins/Insertion/Commands/SearchBookmarkCommand.php
- Plugins/Insertion/Controller/Frontend/FrontendUsersInsertionController.php
- Plugins/Insertion/Models/InsertionUserSearchBookmark.php
- Plugins/Insertion/Services/InsertionSearchBookmarkService.php
- Plugins/Insertion/Views/Frontend/Components/Insertions/SearchBookmarks.twig
- Plugins/Insertion/Views/Frontend/__assets/scss/_search-bookmarks.scss
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Filter/Boolean.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Filter/Date.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Filter/Datemonth.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Filter/Dateyear.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Filter/Distance.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Filter/Multi.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Filter/Number.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Filter/Pedigree.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Filter/Price.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Filter/Range.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/Components/Content/Filter/Single.twig
- Plugins/Insertion/Views/Plugins/Insertion/Frontend/FrontendUsersInsertion/SaveSearchBookmark.twig
- Themes/Base/Frontend/__assets/scss/components/_forms.scss
Fixed SearchBookmarks #222 #223 #362
> Fixed SearchBookmarks #222 #223 #362
